version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: n8n-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: n8n
      MYSQL_USER: n8n_user
      MYSQL_PASSWORD: n8npass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-app
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - DB_TYPE=mysql
      - DB_MYSQLDB_HOST=mysql
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=n8n
      - DB_MYSQLDB_USER=n8n_user
      - DB_MYSQLDB_PASSWORD=n8npass
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=senha123
    depends_on:
      - mysql
    volumes:
      - ./n8n_data:/home/node/.n8n
