# Generated by Django 5.2.8 on 2025-11-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pedidopersonalizado_id_alter_produto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidopersonalizado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
