# Generated by Django 6.0 on 2025-12-09 17:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_interacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'conversas',
                'ordering': ['-ultima_interacao'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('agente', 'Agente')], max_length=20)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='conversas.conversa')),
            ],
            options={
                'db_table': 'mensagens',
                'ordering': ['criado_em'],
            },
        ),
    ]
